module.exports = {
    apps: [
        {
            name: "time-management-app",
            script: ".next/standalone/server.js",
            cwd: "/home/server/time-management-app",
            instances: 1,
            exec_mode: "fork",
            env: {
                NODE_ENV: "production",
                HOSTNAME: "0.0.0.0",
                PORT: "3000",
            },
            error_file: "./logs/err.log",
            out_file: "./logs/out.log",
            log_date_format: "YYYY-MM-DD HH:mm:ss Z",
            merge_logs: true,
            autorestart: true,
            watch: false,
            max_memory_restart: "1G",
        },
        {
            name: "urnik-sync-cron",
            script: "node",
            args: "scripts/build/sync-urnik-cron.js",
            cwd: "/home/server/time-management-app",
            instances: 1,
            exec_mode: "fork",
            env: {
                NODE_ENV: "production",
            },
            error_file: "./logs/cron-err.log",
            out_file: "./logs/cron-out.log",
            log_date_format: "YYYY-MM-DD HH:mm:ss Z",
            merge_logs: true,
            autorestart: true,
            watch: false,
        },
        {
            name: "auto-checkin-checkout-cron",
            script: "node",
            args: "scripts/build/auto-checkin-checkout-cron.js",
            cwd: "/home/server/time-management-app",
            instances: 1,
            exec_mode: "fork",
            env: {
                NODE_ENV: "production",
            },
            error_file: "./logs/auto-checkin-cron-err.log",
            out_file: "./logs/auto-checkin-cron-out.log",
            log_date_format: "YYYY-MM-DD HH:mm:ss Z",
            merge_logs: true,
            autorestart: true,
            watch: false,
        },
    ],
}
